//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housing.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HousingUnit()
        {
            this.HousingDatas = new HashSet<HousingData>();
        }
    
        public int HousingUnitId { get; set; }
        public string HousingUnitName { get; set; }
        public string AptNumber { get; set; }
        public int MaxCapacity { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> HousingComplexId { get; set; }
        public System.DateTime LeaseEndDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual HousingComplex HousingComplex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingData> HousingDatas { get; set; }
    }
}
